name: Smoke Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Run smoke test
        run: ./kannichw smoke-test
        env:
          KANNICH_IMAGE: derkork/kannich@sha256:0f2b3814b8aa71eb1acfefe445a08f73ed415209e34648d561b47c974f7069d7
