name: Smoke Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - uses: derkork/kannich-action@302322e072715e74738f589ead3c167a5735ae35 #v1
        with:
          image: derkork/kannich@sha256:a23067a63c1943b4f24a96bf9841279c2895ce97cc7565133773f6814ae8281e # 0.11.0-0.10.0
          executions: smoke-test
